name: db-update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: sast-efficacy
      - uses: actions/checkout@v2
        with:
          repository: advisory-database
          path: sast-efficacy/advisory-database
      - name: update everything
        run: |
          pip install -r requirements.txt
          python extract_sources.py update
          git commit -m "updated db"
          git push origin master
        working-directory: sast-efficacy